<a href="https://colab.research.google.com/github/narendra974/Pytorch_Bootcamp_ZTM/blob/main/Tensor_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
print("Hello I am Narendra Mutyala excited to learn PyTorch !")

Hello I am Narendra Mutyala excited to learn PyTorch !


In [57]:
!nvidia-smi

Tue Mar 10 16:59:33 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8             15W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [58]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors.

#### Creating tensors.

Pytorch tensors are createed using torch.Tensor() -> https://pytorch.org/docs/stable/tensors.html

In [59]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [60]:
# Attributes of scalar. scalar has no dimensions.

scalar.ndim

0

In [61]:
# to get python int from the tensor.

scalar.item()

7

In [62]:
# Vector has magnnitude and direction.

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [63]:
# number of closing square of brackets.
vector.ndim

1

In [64]:
vector.shape

torch.Size([2])

In [65]:
MATRIX = torch.tensor([ [1, 2],
                        [3, 4] ])

print(MATRIX.ndim) # two square brackets.
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

2
tensor([1, 2])
tensor([3, 4])
torch.Size([2, 2])


In [66]:
#Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9] ]])

### Creating a range of tensors and tensors like (takes the shape and creates those many zeroes or ones)

In [67]:
one_to_thousand = torch.arange(start=1, end = 1000, step = 88)
one_to_thousand

tensor([  1,  89, 177, 265, 353, 441, 529, 617, 705, 793, 881, 969])

In [68]:
ten_zeros = torch.zeros_like(one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
ten_ones = torch.ones_like(one_to_thousand)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes
*** Note : ** Tensor datatypes in one of the 3 big errors you will run in PyTorch and DeepLearning

1. Tensors not right data type use tensor.dtype
2. Tensors not right shape use tensor.shape
3. Tensors not on the right device. use tensor.device

In [70]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               device=None,
                               requires_grad=False,
                               dtype=None) # What dataype is the tensor. check torch.tensor in the google for datatypes.

float_32_tensor
float_32_tensor.dtype

torch.float32

In [71]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [75]:
some_tensor = torch.rand(3, 4)

some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (tensor Operations

1. Addition
2. Subtraction
3. Multiplication ( element -wise)
4. Division
5. Matrix Multiplication


In [76]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [77]:
# multiplciation
tensor * 10

tensor([10, 20, 30])

In [78]:
## Try out Pytorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1.   Element Wise Multiplication
2.   Matrix Multiplication (dot product)



In [79]:
#1 Element wise Mutliplication

tensor * tensor

tensor([1, 4, 9])

In [80]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.59 ms, sys: 0 ns, total: 1.59 ms
Wall time: 5.85 ms


In [94]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 715 µs, sys: 0 ns, total: 715 µs
Wall time: 577 µs


tensor(14)

### one of the most common error is shape error.
### Two main rules that performing matrix multiplication needs to satisfy

1. inner dimensions must match
2. resulting matrix has the shape of the ** outer dimensions **

In [98]:
torch.matmul(torch.rand(2, 10), torch.rand(10, 2))

tensor([[1.5435, 1.9637],
        [2.1559, 1.7346]])