<a href="https://colab.research.google.com/github/narendra974/Pytorch_Bootcamp_ZTM/blob/main/Tensor_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
print("Hello I am Narendra Mutyala excited to learn PyTorch !")

Hello I am Narendra Mutyala excited to learn PyTorch !


In [30]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [31]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors.

#### Creating tensors.

Pytorch tensors are createed using torch.Tensor() -> https://pytorch.org/docs/stable/tensors.html

In [32]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [33]:
# Attributes of scalar. scalar has no dimensions.

scalar.ndim

0

In [34]:
# to get python int from the tensor.

scalar.item()

7

In [35]:
# Vector has magnnitude and direction.

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [36]:
# number of closing square of brackets.
vector.ndim

1

In [37]:
vector.shape

torch.Size([2])

In [38]:
MATRIX = torch.tensor([ [1, 2],
                        [3, 4] ])

print(MATRIX.ndim) # two square brackets.
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

2
tensor([1, 2])
tensor([3, 4])
torch.Size([2, 2])


In [39]:
#Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9] ]])

### Creating a range of tensors and tensors like (takes the shape and creates those many zeroes or ones)

In [40]:
one_to_thousand = torch.arange(start=1, end = 1000, step = 88)
one_to_thousand

tensor([  1,  89, 177, 265, 353, 441, 529, 617, 705, 793, 881, 969])

In [41]:
ten_zeros = torch.zeros_like(one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
ten_ones = torch.ones_like(one_to_thousand)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes
*** Note : ** Tensor datatypes in one of the 3 big errors you will run in PyTorch and DeepLearning

1. Tensors not right data type use tensor.dtype
2. Tensors not right shape use tensor.shape
3. Tensors not on the right device. use tensor.device

In [43]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               device=None,
                               requires_grad=False,
                               dtype=None) # What dataype is the tensor. check torch.tensor in the google for datatypes.

float_32_tensor
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [45]:
some_tensor = torch.rand(3, 4)

some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (tensor Operations

1. Addition
2. Subtraction
3. Multiplication ( element -wise)
4. Division
5. Matrix Multiplication


In [46]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [47]:
# multiplciation
tensor * 10

tensor([10, 20, 30])

In [48]:
## Try out Pytorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1.   Element Wise Multiplication
2.   Matrix Multiplication (dot product)



In [49]:
#1 Element wise Mutliplication

tensor * tensor

tensor([1, 4, 9])

In [50]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 174 µs, sys: 1.04 ms, total: 1.21 ms
Wall time: 2.2 ms


In [51]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 6 µs, sys: 716 µs, total: 722 µs
Wall time: 855 µs


tensor(14)

### one of the most common error is shape error.
### Two main rules that performing matrix multiplication needs to satisfy

1. inner dimensions must match
2. resulting matrix has the shape of the ** outer dimensions **

In [52]:
torch.matmul(torch.rand(2, 10), torch.rand(10, 2))

tensor([[3.6670, 3.1161],
        [3.6106, 2.7491]])

### Finding the min max mean sum etc (tensor aggregation)

In [108]:
#Create a Tensor

x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [109]:
#Fidn the Min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [110]:
#finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [111]:
x = x.type(torch.float32)
torch.mean(x)

tensor(45.)

In [112]:
torch.mean(x.type(torch.float32)) # torch mean function requires a tensor of float32 datatype to work.

tensor(45.)

In [113]:
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

### Fidn the positional min and max

# At which index max or min occurs.

In [114]:
x.argmin(), x[x.argmin()]

(tensor(0), tensor(0.))

In [115]:
x.argmax(), x[x.argmax()]

(tensor(9), tensor(90.))

### Reshaping, Viweing and Stacking Tensors

* Reshaoing - reshapes an input tensor to a defined shape
* View - Return a  view of an input tensor of certain shape but keep the same memory of the original tesnor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze - removes all 1 dimensions froma a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [116]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [117]:
# Add an  extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [118]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [119]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [120]:
# stack tensors on top of each other
x_stacked = torch.stack([z, z, z, z, z])
x_stacked

tensor([[[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]],

        [[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]],

        [[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]],

        [[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]],

        [[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]])

In [121]:
#torch.squeeze() - removes all single dimenstions from a target tensor
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]), torch.Size([9]))

In [122]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]), torch.Size([1, 9]))

In [123]:
print(f'x_shaped tensor shape {x_reshaped.shape}')
x_squeezed = x_reshaped.squeeze()
print(f'x_squeezed tensor shape {x_squeezed.shape}')
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'x_unsqueezed tensor shape {x_unsqueezed.shape}')

x_shaped tensor shape torch.Size([1, 9])
x_squeezed tensor shape torch.Size([9])
x_unsqueezed tensor shape torch.Size([1, 9])


In [124]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
# perfmute is a
x_original = torch.rand(size=(224, 224, 3))
print(f'x_original tensor shape {x_original.shape}')
x_permuted = x_original.permute(2, 0, 1)
print(f'x_permuted tensor shape {x_permuted.shape}')


x_original tensor shape torch.Size([224, 224, 3])
x_permuted tensor shape torch.Size([3, 224, 224])


### Selecting Data from Tensors, Index

Indexing with Pytorch is similarto index with Numpy

In [125]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [126]:
x[0] # indexing on the first dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [127]:
#Let us index on the middle bracket. (dim=1)

x[0][0] # or x(0, 0)

tensor([1, 2, 3])

In [128]:
#Let us index on the most inner bracket
x[0][2][2]

tensor(9)

In [129]:
# YOu can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [130]:
# Get all of the values of 0th and 1st dimensions and index 1 on the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

### PyTOrch tensors and Numpy
Numpy id s popular scientific Python numerical computing library
And because of this, Pytorch has functionality to interact with it

* Data in Numpy, wnat in pytorch, torch.from_numpy(ndarray)
* PyTOrch tensor -> Numpy  torch.Tensor.numpy(tensor)


#numpy default data type is float64
#Tensor default data type is float32.

* use type(torch.float32) to change it to default data type.

In [131]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor_f64 = torch.from_numpy(array)
tensor_f32 = torch.from_numpy(array).type(torch.float32)
array, tensor_f64, tensor_f32

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [132]:
array.dtype, tensor_f64.dtype, tensor_f32.dtype

(dtype('float64'), torch.float64, torch.float32)

In [133]:
# Change the value of array, what will this do 'Tensor'
array = array + 1
array, tensor_f32
# new tensor created is independent of the array memory

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [134]:
tensor = torch.ones(7)   # default data type is float32
numpy_tensor = tensor.numpy() # this will create tensor in #float32 , so to use it further change its datatype.
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Pytorch Reproducability (trying to take random out of random.

In Short how a neural network learns.

`start with random numbers` -> tensor Operations -> updata random numbers to try and make them better representations of the data.->again -> agaom.

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is falvour the randomness.


In [135]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2933, 0.5889, 0.4117, 0.0992],
        [0.3078, 0.7786, 0.8016, 0.3649],
        [0.6286, 0.9663, 0.7687, 0.4566]])
tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [136]:
# Lets nake some random but reproducible tensors

import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)   #we have to reset the random seed.
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Different ways of Accessing a GPU
* Running Tensors and PyTorch objects on the GPUs and making faster computations.
* GPUS = faster computations on numbers, thansk to CUDA + nvidia + torch

### Getting GPU.

* Google Colab Pro
* use your own GPU. https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
* GCP, AWS, Azure

for 2 and 3 PyTorch + GPU setsup takesn time.

In [137]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [139]:
import torch
torch.cuda.is_available()

False

In [141]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [142]:
torch.cuda.device_count()

0

### Putting Tensors and models on GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [143]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [144]:
#Move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to cpu



In [145]:
# If tensor is on GPU, can't transform it to Numpy

tensor_on_gpu.numpy() # since both are in CPU it is working, otherwise it would have throwed error.

array([1, 2, 3])

In [146]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
numpy_on_cpu = tensor_back_on_cpu.numpy()