<a href="https://colab.research.google.com/github/narendra974/Pytorch_Bootcamp_ZTM/blob/main/Tensor_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello I am Narendra Mutyala excited to learn PyTorch !")

Hello I am Narendra Mutyala excited to learn PyTorch !


In [2]:
!nvidia-smi

Mon Jan 26 04:02:15 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   65C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Introduction to Tensors.

#### Creating tensors.

Pytorch tensors are createed using torch.Tensor() -> https://pytorch.org/docs/stable/tensors.html

In [6]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
# Attributes of scalar. scalar has no dimensions.

scalar.ndim

0

In [9]:
# to get python int from the tensor.

scalar.item()

7

In [12]:
# Vector has magnnitude and direction.

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
# number of closing square of brackets.
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [18]:
MATRIX = torch.tensor([ [1, 2],
                        [3, 4] ])

print(MATRIX.ndim) # two square brackets.
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

2
tensor([1, 2])
tensor([3, 4])
torch.Size([2, 2])


In [ ]:
#Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9] ]])