<a href="https://colab.research.google.com/github/narendra974/Pytorch_Bootcamp_ZTM/blob/main/Tensor_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello I am Narendra Mutyala excited to learn PyTorch !")

Hello I am Narendra Mutyala excited to learn PyTorch !


In [2]:
!nvidia-smi

Sat Mar 14 19:23:42 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors.

#### Creating tensors.

Pytorch tensors are createed using torch.Tensor() -> https://pytorch.org/docs/stable/tensors.html

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Attributes of scalar. scalar has no dimensions.

scalar.ndim

0

In [6]:
# to get python int from the tensor.

scalar.item()

7

In [7]:
# Vector has magnnitude and direction.

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# number of closing square of brackets.
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([ [1, 2],
                        [3, 4] ])

print(MATRIX.ndim) # two square brackets.
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

2
tensor([1, 2])
tensor([3, 4])
torch.Size([2, 2])


In [11]:
#Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9] ]])

### Creating a range of tensors and tensors like (takes the shape and creates those many zeroes or ones)

In [12]:
one_to_thousand = torch.arange(start=1, end = 1000, step = 88)
one_to_thousand

tensor([  1,  89, 177, 265, 353, 441, 529, 617, 705, 793, 881, 969])

In [13]:
ten_zeros = torch.zeros_like(one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
ten_ones = torch.ones_like(one_to_thousand)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes
*** Note : ** Tensor datatypes in one of the 3 big errors you will run in PyTorch and DeepLearning

1. Tensors not right data type use tensor.dtype
2. Tensors not right shape use tensor.shape
3. Tensors not on the right device. use tensor.device

In [15]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               device=None,
                               requires_grad=False,
                               dtype=None) # What dataype is the tensor. check torch.tensor in the google for datatypes.

float_32_tensor
float_32_tensor.dtype

torch.float32

In [16]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [17]:
some_tensor = torch.rand(3, 4)

some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (tensor Operations

1. Addition
2. Subtraction
3. Multiplication ( element -wise)
4. Division
5. Matrix Multiplication


In [18]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [19]:
# multiplciation
tensor * 10

tensor([10, 20, 30])

In [20]:
## Try out Pytorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1.   Element Wise Multiplication
2.   Matrix Multiplication (dot product)



In [21]:
#1 Element wise Mutliplication

tensor * tensor

tensor([1, 4, 9])

In [22]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.67 ms, sys: 0 ns, total: 1.67 ms
Wall time: 3.71 ms


In [23]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 818 µs, sys: 0 ns, total: 818 µs
Wall time: 11.5 ms


tensor(14)

### one of the most common error is shape error.
### Two main rules that performing matrix multiplication needs to satisfy

1. inner dimensions must match
2. resulting matrix has the shape of the ** outer dimensions **

In [24]:
torch.matmul(torch.rand(2, 10), torch.rand(10, 2))

tensor([[1.6624, 2.7330],
        [2.4504, 3.4630]])

### Finding the min max mean sum etc (tensor aggregation)

In [25]:
#Create a Tensor

x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [26]:
#Fidn the Min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [27]:
#finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [28]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [29]:
torch.mean(x.type(torch.float32)) # torch mean function requires a tensor of float32 datatype to work.

tensor(45.)

In [31]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Fidn the positional min and max

# At which index max or min occurs.

In [32]:
x.argmin(), x[x.argmin()]

(tensor(0), tensor(0))

In [33]:
x.argmax(), x[x.argmax()]

(tensor(9), tensor(90))

### Reshaping, Viweing and Stacking Tensors

* Reshaoing - reshapes an input tensor to a defined shape
* View - Return a  view of an input tensor of certain shape but keep the same memory of the original tesnor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze - removes all 1 dimensions froma a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [42]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
# Add an  extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [44]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [40]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [47]:
# stack tensors on top of each other
x_stacked = torch.stack([z, z, z, z, z])
x_stacked

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])