<a href="https://colab.research.google.com/github/narendra974/Pytorch_Bootcamp_ZTM/blob/main/Tensor_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello I am Narendra Mutyala excited to learn PyTorch !")

Hello I am Narendra Mutyala excited to learn PyTorch !


In [2]:
!nvidia-smi

Tue Mar 10 16:41:55 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   68C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


## Introduction to Tensors.

#### Creating tensors.

Pytorch tensors are createed using torch.Tensor() -> https://pytorch.org/docs/stable/tensors.html

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Attributes of scalar. scalar has no dimensions.

scalar.ndim

0

In [6]:
# to get python int from the tensor.

scalar.item()

7

In [7]:
# Vector has magnnitude and direction.

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# number of closing square of brackets.
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([ [1, 2],
                        [3, 4] ])

print(MATRIX.ndim) # two square brackets.
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

2
tensor([1, 2])
tensor([3, 4])
torch.Size([2, 2])


In [11]:
#Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9] ]])

### Creating a range of tensors and tensors like (takes the shape and creates those many zeroes or ones)

In [15]:
one_to_thousand = torch.arange(start=1, end = 1000, step = 88)
one_to_thousand

tensor([  1,  89, 177, 265, 353, 441, 529, 617, 705, 793, 881, 969])

In [16]:
ten_zeros = torch.zeros_like(one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
ten_ones = torch.ones_like(one_to_thousand)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)